compile : gnuplot_euler.c gnuplot_lorenz.c
	gcc -I ../../include/gnuplot_lib/ -I ../../include/euler_lib/ -I ../../include/lorenz_lib/ -c *.c
	mv gnuplot_euler.o ../euler_src/
	mv gnuplot_lorenz.o ../lorenz_src/
