compile : input_euler.c input_lorenz.c
	gcc -I ../../include/input_lib/ -I ../../include/euler_lib/ -I ../../include/lorenz_lib/ -c *.c
	mv input_euler.o ../euler_src/
	mv input_lorenz.o ../lorenz_src/
