compile : displayShell_euler.c displayShell_lorenz.c
	gcc -I ../../include/displayShell_lib/ -I ../../include/euler_lib/ -I ../../include/lorenz_lib/ -c *.c
	mv displayShell_euler.o ../euler_src/
	mv displayShell_lorenz.o ../lorenz_src/
